spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:handson-account
    username: sa
    password: sa
    jpa:
      open-in-view: false
      hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        ddl-auto: validate
        properties:
          hibernate.format_sql: true
          hibernate.enable_lazy_load_no_trans: true
    flyway:
      location: ["classpath:db/migration"]

eureka:
  client:
    service-url:
      default-zone: http://kgtiger/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org.springframework.web: info

say:
  cheese: bye~~~~~~~